#!/bin/bash

echo "* Starting node Node-1 ..."

/usr/bin/geth --testnet --rpc --rpcaddr "0.0.0.0" --rpcport "8545" --port "30303" --rpccorsdomain "*" \
--fast --cache=2048 \
--unlock "0x0942e9144606ad43f2e61a7ee332fe9914424712" --password /data/pw.txt \
--datadir "/data/node-1" --rpcapi "db,eth,net,web3,admin,personal"

s6-svc -d /var/run/s6/services/node-bob
