#!/bin/bash

echo "* Starting node ..."

/usr/bin/geth --testnet --rpc --rpcaddr "0.0.0.0" --rpcport "8545" --rpccorsdomain "*" \
--unlock "0x0942e9144606ad43f2e61a7ee332fe9914424712" --password /data/pw.txt \
--verbosity 5 \
--datadir "/data" --rpcapi "db,eth,net,web3,admin,personal"

s6-svc -d /var/run/s6/services/node-bob
